### PR TITLE
[EDIFIKANA] #132 Implement error handling BE

### LINKED ISSUE #132: [TASK] Implement better error handling
**Describe the task to complete**
We need to be able to map our error and exceptions to corresponding HTTP codes and error messaging for more clarity for us and users. 

**How should we implement this (high level)?**
See `ClientRequestExceptions` for our foundation and build upon this before implementing the OTP validation through email.

**What type of task is this?**
Improvement

### PR DESCRIPTION
**Pull request by gaaliciA1990**
#132 
Updated `UserControlUtils` and `SupabaseUserDB` to map errors/exceptions to our `ClientRequestExceptions` class errors. 
Added tests to cover the error handling messages and updated related files.

### CODE REVIEW

File: edifikana/back-end/src/main/kotlin/com/cramsan/edifikana/server/core/controller/ControllerUtils.kt [hunk 1]
```diff
@@ -43,17 +45,79 @@ suspend inline fun ApplicationCall.handleCall(
...
+ * @param result The result of the function call.
+ */
+suspend inline fun ApplicationCall.validateClientError(
+    result: Result<HttpResponse>,
+) {
+    // Handle the error based on our created exceptions.
+    val originalException = result.exceptionOrNull()
+    val exception = originalException as? ClientRequestExceptions
+    if (exception == null) {
+        logE(tag, "Unexpected failure when handing request")
```
Comment (CRamsan) [inline edifikana/back-end/src/main/kotlin/com/cramsan/edifikana/server/core/controller/ControllerUtils.kt:72]: Let's log the exception as part of this `logE` line. The third parameter in `logE` is an exception.

`logE(tag, "Unexpected failure when handing request", originalException)`

Comment (gaaliciA1990) [reply edifikana/back-end/src/main/kotlin/com/cramsan/edifikana/server/core/controller/ControllerUtils.kt:72]: Addressed in latest commit

**Review by CRamsan — APPROVED** [review]
